FROM nginx:alpine

# Hapus config default
RUN rm -f /etc/nginx/conf.d/default.conf

# Copy config custom
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

HEALTHCHECK --interval=15s --timeout=5s --retries=5 \
    CMD wget -qO- http://localhost/health || exit 1


